version: "3.5"

services:
  shishabot:
    build: .
    environment:
      - BOT_AUTHTOKEN=NzcxNDYyMjkyMTc1ODQ3NDY0.X5sePw.d8yT7NAnKjJOWixTAS_bKZDGR6M
      - BOT_DEFAULTMESSAGE="Bock auf Shisha?"
      - BOT_DEFAULTYESMESSAGE="https://www.youtube.com/watch?v=4A505Hl1JSg"
      - BOT_DEFAULTNOMESSAGE="ok"
      - BOT_ERRORMESSAGE="sth went wrong"
      - BOT_INTERVAL="604800"
      - BOT_MAXTIME="86400"
    volumes:
      - ./shishabot/data:/usr/src/app/data
